CREATE TABLE CHINHANH (
    MaChiNhanh INT NOT NULL AUTO_INCREMENT,
    Tinh VARCHAR(50),
    DiaChi VARCHAR(255),
    DienThoai DECIMAL(11 , 0 ),
    Email VARCHAR(50),
    PRIMARY KEY (MaChiNhanh)
);

/* TRIGGER */
CREATE 
    TRIGGER  AddPrefix
 BEFORE INSERT ON CHINHANH FOR EACH ROW 
    SET NEW . MaChiNhanh = CONCAT('CN', MaChiNhanh);