CREATE TABLE CHINHANH (
    MaChiNhanh VARCHAR(50) NOT NULL AUTO_INCREMENT,
    Tinh VARCHAR(50) NOT NULL,
    DiaChi VARCHAR(255) NOT NULL,
    DienThoai INT NOT NULL,
    Email VARCHAR(50) NOT NULL,
    PRIMARY KEY (MaChiNhanh)
);
CREATE TABLE HINHANH_CHINHANH (
    HA_MCN INT NOT NULL,
    HinhAnh JSON NOT NULL,
    PRIMARY KEY (HA_MCN,HinhAnh),
    FOREIGN KEY (HA_MCN)
		REFERENCES CHINHANH(MaChiNhanh)
);
CREATE TABLE KHU (
    Khu_MCN VARCHAR(50) NOT NULL,
    TenKhu VARCHAR(50) NOT NULL,
    PRIMARY KEY (Khu_MCN , TenKhu),
    FOREIGN KEY (Khu_MCN)
        REFERENCES CHINHANH (MaChiNhanh)
);
CREATE TABLE LOAIPHONG (
    MaLoaiPhong INT NOT NULL AUTO_INCREMENT,
    TenLoaiPhong VARCHAR(50) NOT NULL,
    DienTich DECIMAL(3 , 2 ) NOT NULL,
    SoKhach INT UNIQUE CHECK (SoKhach > 0 AND SoKhach < 11),
    MoTaKhac VARCHAR(255) DEFAULT NULL,
    PRIMARY KEY (MaLoaiPhong)
);
CREATE TABLE THONGTINGIUONG (
    TTG_MLP INT NOT NULL,
    KichThuoc DECIMAL(1 , 1 ) NOT NULL,
    SoLuong INT NOT NULL CHECK(SoLuong > 0 and SoLuong < 11) DEFAULT 1,
    PRIMARY KEY (TTG_MLP, KichThuoc),
    FOREIGN KEY (TTG_MLP) REFERENCES LOAIPHONG(MaLoaiPhong)
);
CREATE TABLE CHINHANH_CO_LOAIPHONG (
    Co_MLP INT NOT NULL,
    Co_MCN VARCHAR(50) NOT NULL,
    GiaThue INT NOT NULL,						/* Add Unit (1000 vnd) */
    PRIMARY KEY (Co_MLP , Co_MCN),
    FOREIGN KEY (Co_MLP)
        REFERENCES LOAIPHONG (MaLoaiPhong),
    FOREIGN KEY (Co_MCN)
        REFERENCES CHINHANH (MaChiNhanh)
);
CREATE TABLE PHONG (
    Phong_MCN VARCHAR(50) NOT NULL,
    Phong_SP VARCHAR(50) NOT NULL
);

/* TRIGGER */
CREATE 
    TRIGGER  AddPrefix_MCN
 AFTER INSERT ON CHINHANH FOR EACH ROW 
    SET NEW . MaChiNhanh = CONCAT('CN', MaChiNhanh);