CREATE TABLE CHINHANH (
    MaChiNhanh INT NOT NULL AUTO_INCREMENT,
    Tinh VARCHAR(50),
    DiaChi VARCHAR(255),
    DienThoai DECIMAL(11 , 0 ),
    Email VARCHAR(50),
    PRIMARY KEY (MaChiNhanh)
);

CREATE TABLE MAKHACHHANG(
	MaKhachHang CHAR(8) NOT NULL CHECK(CAST(MaKhachhang AS UNSIGNED INT) < 1000000),
	CCCD VARCHAR(12) NOT NULL UNIQUE,
	Email VARCHAR(50) NOT NULL,
	Username VARCHAR(50) NOT NULL,
	Diem INT NOT NULL CHECK(Diem > -1) DEFAULT 0,
	Loai INT NOT NULL CHECK(Loai > 0) DEFAULT 1, /*NEEDS A VIEW*/
	PRIMARY KEY (MaKhachHang)
);

CREATE TABLE GoiDichVu (
	TenGoi VARCHAR(50),
	SoNgay INT NOT NULL CHECK(SoNgay > 0 AND SoNgay < 101),
	SoKhach INT NOT NULL Check(SoKhach > 0 AND SoKhach < 11),
	PRIMARY KEY (TenGoi)
);

CREATE TABLE HOADONGOIDICHVU (
	HDGDV_MKH CHAR(8) NOT NULL CHECK(CAST(MaKhachhang AS UNSIGNED INT) < 1000000),
    HDGDV_TG VARCHAR(50),
    NgayGioMua DateTime NOT NULL,
    NgayBatDau DateTime NOT NULL CHECK (NgayBatDau > NgayGioMua),
    TongTien INT NOT NULL,
    FOREIGN KEY (HDGDV_MKH) REFERENCES KHACHHANG(MaKhachHang),
    FOREIGN KEY (HDGDV_TG) REFERENCES GOIDICHVU(TenGoi),
    PRIMARY KEY (HDGDV_MKH, HDGDV_TG, NgayGioMua)
);

CREATE TABLE DonDatPhong (
    MaDatPhong VARCHAR(16) AUTO_INCREMENT,
    NgayGioDat DATETIME NOT NULL,
    NgayNhanPhong DATETIME NOT NULL CHECK (NgayNhanPhong > NgayGioDat),
    NgayTraPhong DATETIME NOT NULL CHECK (NgayTraPhong > NgayNhanPhong),
    TinhTrang INT CHECK (TinhTrang > - 1 AND TinhTrang < 4),
    PRIMARY KEY (MaDatPhong)
);

CREATE TABLE PHONGTHUE (
    PT_MDP VARCHAR(16) AUTO_INCREMENT,
    PT_MCN INT NOT NULL AUTO_INCREMENT,
    PT_SP VARCHAR(3) NOT NULL,
    FOREIGN KEY (PT_MDP)
        REFERENCES DONDATPHONG (MaDatPhong),
    FOREIGN KEY (PT_MCN)
        REFERENCES CHINHANH (MaChiNhanh),
    FOREIGN KEY (PT_SP)
        REFERENCES PHONG (SoPhong),
    PRIMARY KEY (PT_MDP , PT_MCN , PT_SP)
);

CREATE TABLE HOADON(
	MaHoaDon VARCHAR(16) AUTO_INCREMENT,
    ThoiGianTraPhong REFERENCES DONDATPHONG(NgayTraPhong)
);

/* TRIGGER */
CREATE 
    TRIGGER  AddPrefix_MCN
AFTER INSERT ON CHINHANH FOR EACH ROW 
    SET NEW . MaChiNhanh = CONCAT('CN', MaChiNhanh);
    
CREATE 
    TRIGGER  AddPrefix_MDP
 AFTER INSERT ON DONDATPHONG FOR EACH ROW 
    SET NEW . MaDatPhong = CONCAT('DP', CURDATE(), MaDatPhong);

CREATE 
    TRIGGER  AddPrefix_MHD
 AFTER INSERT ON HOADON FOR EACH ROW 
    SET NEW . MaHoaDon = CONCAT('HD', CURDATE(), MaHoaDon);
    
/* VIEW */
CREATE VIEW NgayNhanPhong AS
SELECT DATE(NgayNhanPhong) AS NgayNhanPhong FROM DONDATPHONG;